### PR TITLE
Add History & allow CORS when start nodeos

### PR DESCRIPTION
**Pull request by DenisCarriere**
Add history plugin & allows CORS

Allows to test using localhost bloks.io

https://local.bloks.io/account/thisisbancor?nodeUrl=localhost%3A8888&systemDomain=eosio

### CODE REVIEW

**Comment by DenisCarriere** [comment]
image

**Comment by ricktobacco** [comment]
We need the *.wasm for eosio.contracts binaries, and we prefer to also provide our compiled contracts' binaries for convenience :)
But the stderror, nodeos folder, and lockfile can indeed be excluded, thank you!

**Comment by ricktobacco** [comment]
Hello again :)
I appreciate your CORS addition to the nodeos script (haven't used local.bloks before, but I love the idea), and cleaning up the general presentation by making it multi-line...
noticed you also added several extras:
* chain_plugin
* history_plugin
* state_history_plugin
* --replay-blockchain
* --hard-replay-blockchain
* --filter-on=* 
* --filter-out=eosio:onblock: 
* --trace-history
* --chain-state-history
* --disable-replay-opts
curious to understand the reasoning for this, also local.bloks dependencies?

**Comment by DenisCarriere** [comment]
There’s many block explorers that now allow to connect to your local nodeos instance, it’s pretty handy to visualize your contract via a block explorer compared to using cleos

The CORS addition is standard for websites, without it you can’t fetch data from an external source

**Pull request merged**
